### ISSUE TITLE
How to define gradle config for the provided Maven exec plugin configuration ?

### ISSUE THREAD

**Issue by rkbala** [grasshopper7/testcukefeatproc#1]
I referred the link here: https://grasshopper.tech/418/

I want to read the test data from excel for cucumber features and scenarios. Please help.

**Comment by rkbala** [comment]
@grasshopper7

**Comment by grasshopper7** [comment]
You can refer to this - https://stackoverflow.com/questions/16350757/what-is-the-gradle-equivalent-of-mavens-exec-plugin-for-running-java-apps
